#!/usr/bin/env ${PYTHON}

import sys
import xhtml
import time
import string

def do_file(filename):

    fp = open(filename, "r")
    print "<!-- This file automatically generated by mirrorfmt_json.py $Revision$ -->"
    print "<!-- DO NOT EDIT THIS FILE - edit the master file MIRRORS.in instead -->"

    print '"mirrors_http":[\n'

    for l in fp:
        l = l.rstrip()
        if len(l) > 1:
            if l[0] == "#":
                pass
            else:
                l = l.lstrip()
                idx = 0
                while idx < len(l) and l[idx] not in string.whitespace:
                    idx = idx + 1
                if idx < len(l):
                    # split the link (before whitespace) from the comment
                    if l.startswith("http"):
                        print '"' + l[0:idx] + '",'
                else:
                    if l.startswith("http"):
                        print '"' + l[0:idx] + '",'
                pass
            pass
        pass

    print "];"
    fp.close()

    return

def main(argv):
    for a in argv:
        do_file(a)
        pass

    return

main(sys.argv[1:])
