GIMP_VERSION_STABLE = '2.8.18'
GIMP_VERSION_DEVEL  = '2.9.4'

GIMP_VERSION_STABLE_WINDOWS = '2.8.18'
GIMP_VERSION_STABLE_MACOS   = '2.8.16'

GIMP_VERSION_STABLE_WINDOWS_POSTFIX = ''
GIMP_VERSION_STABLE_MACOS_POSTFIX = '-1'
