#!/usr/bin/perl

use Gimp;
use Gimp::Fu;

podregister {
  my $img = Gimp::Image->new(350, 100, RGB);
  my $drw = $img->layer_new($img->width, $img->height,
			RGB, "BG", 100, NORMAL_MODE);
  $img->insert_layer($drw, -1, 0);
  Gimp::Context->set_background("black");
  $drw->edit_fill(BACKGROUND_FILL);
  Gimp::Context->set_foreground([255,255,0]); # Choose color of text
  # Create the text
  my $textlayer = $drw->text_fontname(0, 0, $text, 10, 1, $size, POINTS, $font);
  $textlayer->floating_sel_anchor;
  Gimp::Display->new($img);
  return $img;
};

exit main;
__END__

=head1 NAME

hello_world1 - basic text

=head1 SYNOPSIS

<Image>/File/Create/Tutorial/Basic text 1

=head1 DESCRIPTION

basic text

=head1 PARAMETERS

 [PF_FONT, "font", "Font", "Sans"],
 [PF_INT32, "size", "Font size", 70],
 [PF_STRING, "text", "Text", "Hello world!"]

=head1 AUTHOR

Dov

=head1 DATE

2004-03-27

=head1 LICENSE

Dov
