#!/usr/bin/perl

use Gimp;
use Gimp::Fu;

podregister {
  # Create the background
  my $img = Gimp::Image->new($size, $size, RGB);
  $layer = $img->layer_new($size, $size, RGB, "Layer 1", 100, NORMAL_MODE);
  $img->insert_layer($layer, -1, 0);
  Gimp::Context->set_background($bgcolor);
  $layer->edit_fill(BACKGROUND_FILL);
  my $ncircles = int($size/$radius/2);
  for ($i=0; $i<$ncircles; $i++) {
    for ($j=0; $j<$ncircles; $j++) {
      # Select a circle
      $img->select_ellipse(
	CHANNEL_OP_REPLACE, $i*$radius*2, $j*$radius*2, $radius*2, $radius*2
      );
      my $color = [$i*30, ($ncircles-$j)*25, ($i+$j)*15]; # mix colors
      Gimp::Context->set_background($color);
      $layer->edit_fill(BACKGROUND_FILL);
    }
  }
  Gimp::Display->new($img);
  return $img;
};

exit main;
__END__

=head1 NAME

circles - a loop

=head1 SYNOPSIS

<Image>/File/Create/Tutorial/Circles

=head1 DESCRIPTION

a loop

=head1 PARAMETERS

 [PF_INT32, "size", "Image size", 100],
 [PF_COLOR, "bgcolor", "Background color", [40,180,60]],
 [PF_INT32, "radius", "Circle radius", 10]

=head1 AUTHOR

Dov

=head1 DATE

1999-05-14

=head1 LICENSE

Dov
