#!/usr/bin/perl -w

use strict;
use Gimp;
use Gimp::Fu;

podregister {
  # no need to have my ($size, $color) = @_;
  my $img = Gimp::Image->new($size, $size, RGB); # Create a new image
  # Create a new layer
  my $layer = $img->layer_new($size, $size, RGB, "Layer 1", 100, NORMAL_MODE);
  $img->insert_layer($layer, -1, 0); # add the layer to the image
  Gimp::Context->set_background($color); # Set background to required color
  $layer->edit_fill(BACKGROUND_FILL); # Paint the layer 
  Gimp::Display->new($img);
  return $img; # Return image - return implied by no IMAGE TYPES
};

exit main;
__END__

=head1 NAME

img_uni - Create a uniform image

=head1 SYNOPSIS

<Image>/File/Create/Tutorial/Img Uni

=head1 DESCRIPTION

A tutorial script.

=head1 PARAMETERS

 [PF_INT32,   "size", "Img size", 100],
 [PF_COLOR, "color", "Img color", [255,127,0]]

=head1 AUTHOR

Dov Grobgeld

=head1 DATE

2004-03-27

=head1 LICENSE

Dov Grobgeld (c)
